/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Pharmacy {
  'id' : bigint,
  'lat' : number,
  'lng' : number,
  'nom' : string,
  'tel' : string,
  'statut' : string,
  'ouvert' : boolean,
  'codeSecret' : string,
  'email' : string,
  'approuve' : boolean,
  'visible' : boolean,
  'adresse' : string,
}
export interface RegisterResult { 'id' : bigint, 'code' : string }
export interface SubmitResult { 'id' : bigint, 'code' : string }
export interface UserProfile {
  'name' : string,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deletePharmacy' : ActorMethod<[bigint], boolean>,
  'getAllPharmacies' : ActorMethod<[], Array<Pharmacy>>,
  'getApprovedPharmacies' : ActorMethod<[], Array<Pharmacy>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPharmacyByCode' : ActorMethod<[string], [] | [Pharmacy]>,
  'getPharmacyByEmail' : ActorMethod<[string], [] | [Pharmacy]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeSeedData' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'loginPharmacist' : ActorMethod<[string, string], [] | [Pharmacy]>,
  'registerPharmacist' : ActorMethod<
    [string, string, string, string, boolean],
    RegisterResult
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setPharmacyOpenStatus' : ActorMethod<[bigint, boolean], boolean>,
  'submitPharmacy' : ActorMethod<[string, string, string], SubmitResult>,
  'togglePharmacyVisibility' : ActorMethod<[bigint], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];