/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Pharmacy = IDL.Record({
  'id' : IDL.Nat,
  'lat' : IDL.Float64,
  'lng' : IDL.Float64,
  'nom' : IDL.Text,
  'tel' : IDL.Text,
  'statut' : IDL.Text,
  'ouvert' : IDL.Bool,
  'approuve' : IDL.Bool,
  'visible' : IDL.Bool,
  'adresse' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'approvePharmacy' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllPharmacies' : IDL.Func([], [IDL.Vec(Pharmacy)], ['query']),
  'getApprovedPharmacies' : IDL.Func([], [IDL.Vec(Pharmacy)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPharmacyByName' : IDL.Func([IDL.Text], [IDL.Opt(Pharmacy)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeSeedData' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'rejectPharmacy' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'revokePharmacy' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setPharmacyOpenStatus' : IDL.Func([IDL.Nat, IDL.Bool], [IDL.Bool], []),
  'submitPharmacy' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'togglePharmacyVisibility' : IDL.Func([IDL.Nat], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Pharmacy = IDL.Record({
    'id' : IDL.Nat,
    'lat' : IDL.Float64,
    'lng' : IDL.Float64,
    'nom' : IDL.Text,
    'tel' : IDL.Text,
    'statut' : IDL.Text,
    'ouvert' : IDL.Bool,
    'approuve' : IDL.Bool,
    'visible' : IDL.Bool,
    'adresse' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'approvePharmacy' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllPharmacies' : IDL.Func([], [IDL.Vec(Pharmacy)], ['query']),
    'getApprovedPharmacies' : IDL.Func([], [IDL.Vec(Pharmacy)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPharmacyByName' : IDL.Func([IDL.Text], [IDL.Opt(Pharmacy)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeSeedData' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'rejectPharmacy' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'revokePharmacy' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setPharmacyOpenStatus' : IDL.Func([IDL.Nat, IDL.Bool], [IDL.Bool], []),
    'submitPharmacy' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
    'togglePharmacyVisibility' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };